#!/usr/bin/env python3
"""
IBM Design Language PDF Generator
Permanent script -- not regenerated by LLM each time.
Usage: python3 generate_ibm_pdf.py <markdown_file> <output_pdf>
       [--cover] [--title TITLE] [--subtitle SUBTITLE] [--description DESC]
       [--date DATE] [--team TEAM] [--font-dir FONT_DIR]
"""

import os, re, sys, argparse
from functools import partial
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether
)
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus.flowables import Flowable

# ============================================================
# 1. FONTS
# ============================================================
# Font registration is deferred until build_document() runs so that
# `--help` and argparse errors don't crash on missing TTF files.

FONT_NAMES = ["Light", "Regular", "Medium", "SemiBold", "Bold",
              "Italic", "LightItalic", "MediumItalic", "SemiBoldItalic", "BoldItalic"]


def _resolve_font_dir(cli_font_dir=None):
    """Pick the first existing font directory from the resolution chain:
    1. --font-dir CLI flag
    2. ~/Documents/IBM_Plex_Sans/static
    3. <skill>/assets/fonts (relative to this script)
    4. /Library/Fonts (macOS system fonts)
    5. ~/Library/Fonts (macOS user fonts)
    6. /usr/share/fonts (Linux system fonts)
    7. ~/.local/share/fonts (Linux user fonts)
    
    For system directories, we check if IBM Plex Sans fonts exist before
    returning the directory.
    Returns the chosen path, or None if none exist."""
    candidates = []
    
    # Priority 1-3: Explicit locations (existing behavior)
    if cli_font_dir:
        candidates.append(os.path.expanduser(cli_font_dir))
    candidates.append(os.path.expanduser("~/Documents/IBM_Plex_Sans/static"))
    candidates.append(os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "assets", "fonts"
    ))
    
    # Check explicit candidates first
    for c in candidates:
        if c and os.path.isdir(c):
            return c
    
    # Priority 4-7: System font directories
    # Only return these if they contain IBM Plex Sans fonts
    system_candidates = [
        "/Library/Fonts",                           # macOS system
        os.path.expanduser("~/Library/Fonts"),      # macOS user
        "/usr/share/fonts",                         # Linux system
        os.path.expanduser("~/.local/share/fonts"), # Linux user
    ]
    
    for sys_dir in system_candidates:
        if os.path.isdir(sys_dir):
            # Check if IBM Plex Sans fonts exist in this directory
            # Look for at least one IBMPlexSans-*.ttf file
            try:
                for entry in os.listdir(sys_dir):
                    if entry.startswith("IBMPlexSans-") and entry.endswith(".ttf"):
                        return sys_dir
                # Also check subdirectories (fonts might be in IBM_Plex_Sans/ subfolder)
                for entry in os.listdir(sys_dir):
                    subdir = os.path.join(sys_dir, entry)
                    if os.path.isdir(subdir) and "plex" in entry.lower():
                        for subentry in os.listdir(subdir):
                            if subentry.startswith("IBMPlexSans-") and subentry.endswith(".ttf"):
                                return subdir
            except (OSError, PermissionError):
                continue
    
    return None


def _download_ibm_plex_fonts():
    """Download IBM Plex Sans fonts from GitHub to ~/Documents/IBM_Plex_Sans/static.
    Returns True if successful, False otherwise."""
    import urllib.request
    import zipfile
    import tempfile
    
    target_dir = os.path.expanduser("~/Documents/IBM_Plex_Sans/static")
    
    print("\nDownloading IBM Plex Sans fonts from GitHub...", file=sys.stderr)
    
    try:
        # IBM Plex Sans GitHub release URL
        zip_url = "https://github.com/IBM/plex/releases/download/v6.4.0/TrueType.zip"
        
        # Download to temp file
        with tempfile.NamedTemporaryFile(delete=False, suffix='.zip') as tmp_file:
            tmp_path = tmp_file.name
            print(f"Downloading from {zip_url}...", file=sys.stderr)
            urllib.request.urlretrieve(zip_url, tmp_path)
        
        # Extract IBM Plex Sans fonts
        os.makedirs(target_dir, exist_ok=True)
        
        with zipfile.ZipFile(tmp_path, 'r') as zip_ref:
            # Extract only IBM Plex Sans static fonts
            for file_info in zip_ref.filelist:
                if 'IBM-Plex-Sans/fonts/complete/ttf/' in file_info.filename and file_info.filename.endswith('.ttf'):
                    # Extract just the filename
                    filename = os.path.basename(file_info.filename)
                    if filename:  # Skip directory entries
                        target_path = os.path.join(target_dir, filename)
                        with zip_ref.open(file_info) as source, open(target_path, 'wb') as target:
                            target.write(source.read())
        
        # Clean up temp file
        os.unlink(tmp_path)
        
        # Verify fonts were extracted
        fonts = [f for f in os.listdir(target_dir) if f.startswith('IBMPlexSans-') and f.endswith('.ttf')]
        if fonts:
            print(f"✓ Successfully downloaded {len(fonts)} IBM Plex Sans fonts to {target_dir}", file=sys.stderr)
            return True
        else:
            print(f"✗ Download completed but no fonts found in {target_dir}", file=sys.stderr)
            return False
            
    except Exception as e:
        print(f"✗ Failed to download fonts: {e}", file=sys.stderr)
        return False


def _prompt_for_font_location():
    """Interactively prompt user for font location or offer to download.
    Returns font directory path or None."""
    print("\n" + "="*70, file=sys.stderr)
    print("IBM Plex Sans fonts not found in standard locations.", file=sys.stderr)
    print("="*70, file=sys.stderr)
    print("\nOptions:", file=sys.stderr)
    print("  1. Download fonts automatically from IBM GitHub (recommended)", file=sys.stderr)
    print("  2. Specify a custom directory where fonts are installed", file=sys.stderr)
    print("  3. Continue with default fonts (PDF will not match IBM branding)", file=sys.stderr)
    print("\nSearched locations:", file=sys.stderr)
    print("  - ~/Documents/IBM_Plex_Sans/static", file=sys.stderr)
    print("  - ~/.bob/skills/document-conversion/assets/fonts", file=sys.stderr)
    print("  - /Library/Fonts", file=sys.stderr)
    print("  - ~/Library/Fonts", file=sys.stderr)
    print("  - /usr/share/fonts", file=sys.stderr)
    print("  - ~/.local/share/fonts", file=sys.stderr)
    
    try:
        choice = input("\nEnter your choice (1-3): ").strip()
        
        if choice == "1":
            if _download_ibm_plex_fonts():
                return os.path.expanduser("~/Documents/IBM_Plex_Sans/static")
            else:
                print("\nDownload failed. Continuing with default fonts.", file=sys.stderr)
                return None
                
        elif choice == "2":
            custom_path = input("Enter the full path to your IBM Plex Sans font directory: ").strip()
            custom_path = os.path.expanduser(custom_path)
            
            if os.path.isdir(custom_path):
                # Verify fonts exist
                fonts = [f for f in os.listdir(custom_path) if f.startswith('IBMPlexSans-') and f.endswith('.ttf')]
                if fonts:
                    print(f"✓ Found {len(fonts)} IBM Plex Sans fonts in {custom_path}", file=sys.stderr)
                    return custom_path
                else:
                    print(f"✗ No IBM Plex Sans fonts found in {custom_path}", file=sys.stderr)
                    print("Continuing with default fonts.", file=sys.stderr)
                    return None
            else:
                print(f"✗ Directory not found: {custom_path}", file=sys.stderr)
                print("Continuing with default fonts.", file=sys.stderr)
                return None
                
        else:  # choice == "3" or invalid
            print("\nContinuing with default fonts.", file=sys.stderr)
            return None
            
    except (KeyboardInterrupt, EOFError):
        print("\n\nInterrupted. Continuing with default fonts.", file=sys.stderr)
        return None


def register_fonts(cli_font_dir=None, interactive=True):
    """Register IBM Plex Sans fonts. Each TTFont call is wrapped in
    try/except so missing files don't crash the run -- ReportLab will
    fall back to its built-in default font.
    
    Args:
        cli_font_dir: Optional font directory from --font-dir CLI flag
        interactive: If True, prompt user when fonts not found (default: True)
    """
    font_dir = _resolve_font_dir(cli_font_dir)
    
    # If no fonts found and interactive mode, offer to download or locate
    if not font_dir and interactive:
        font_dir = _prompt_for_font_location()
    
    if not font_dir:
        print(
            "\nWARNING: No IBM Plex Sans fonts available. "
            "PDF will use default fonts and will not match IBM branding.\n",
            file=sys.stderr,
        )
        return False

    registered_any = False
    for name in FONT_NAMES:
        path = os.path.join(font_dir, f"IBMPlexSans-{name}.ttf")
        try:
            pdfmetrics.registerFont(TTFont(f"IBMPlexSans-{name}", path))
            registered_any = True
        except Exception as e:
            print(
                f"WARNING: Failed to register font IBMPlexSans-{name} "
                f"from {path}: {e}",
                file=sys.stderr,
            )

    if registered_any:
        try:
            pdfmetrics.registerFontFamily(
                "IBMPlexSans",
                normal="IBMPlexSans-Regular",
                bold="IBMPlexSans-Bold",
                italic="IBMPlexSans-Italic",
                boldItalic="IBMPlexSans-BoldItalic",
            )
        except Exception as e:
            print(f"WARNING: Failed to register IBMPlexSans family: {e}", file=sys.stderr)
    return registered_any

# ============================================================
# 2. COLORS
# ============================================================
BLUE_10  = HexColor("#edf5ff")
BLUE_20  = HexColor("#d0e2ff")
BLUE_30  = HexColor("#a6c8ff")
BLUE_40  = HexColor("#78a9ff")
BLUE_60  = HexColor("#0f62fe")
BLUE_80  = HexColor("#002d9c")
BLUE_90  = HexColor("#001d6c")
GRAY_10  = HexColor("#f4f4f4")
GRAY_20  = HexColor("#e0e0e0")
GRAY_50  = HexColor("#8d8d8d")
GRAY_60  = HexColor("#6f6f6f")
GRAY_70  = HexColor("#525252")
GRAY_100 = HexColor("#161616")
WHITE    = HexColor("#ffffff")
CYAN_09  = HexColor("#e5f6ff")
CYAN_11  = HexColor("#82cfff")
GREEN_60 = HexColor("#198038")
RED_60   = HexColor("#da1e28")
COVER_BG = HexColor("#071c68")

# ============================================================
# 3. PAGE LAYOUT
# ============================================================
PAGE_W, PAGE_H = letter
LEFT_MARGIN   = 0.75 * inch
RIGHT_MARGIN  = 0.75 * inch
TOP_MARGIN    = 0.75 * inch
BOTTOM_MARGIN = 0.85 * inch
CONTENT_W     = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

# ============================================================
# 4. PARAGRAPH STYLES
# ============================================================
section_title_style = ParagraphStyle(
    "SectionTitle", fontName="IBMPlexSans-Light", fontSize=32, leading=36,
    textColor=GRAY_100, spaceBefore=0, spaceAfter=6,
)
h2_style = ParagraphStyle(
    "H2", fontName="IBMPlexSans-Medium", fontSize=16, leading=22,
    textColor=GRAY_100, spaceBefore=16, spaceAfter=6,
)
h3_style = ParagraphStyle(
    "H3", fontName="IBMPlexSans-Medium", fontSize=12, leading=17,
    textColor=GRAY_100, spaceBefore=12, spaceAfter=5,
)
body_style = ParagraphStyle(
    "Body", fontName="IBMPlexSans-Regular", fontSize=9.5, leading=14.5,
    textColor=GRAY_100, spaceBefore=0, spaceAfter=6, alignment=TA_LEFT,
)
bullet_style = ParagraphStyle(
    "Bullet", fontName="IBMPlexSans-Regular", fontSize=9.5, leading=14.5,
    textColor=GRAY_100, spaceBefore=0, spaceAfter=3,
    leftIndent=18, bulletIndent=0,
    bulletFontName="IBMPlexSans-Regular", bulletFontSize=9.5,
)
sub_bullet_style = ParagraphStyle(
    "SubBullet", fontName="IBMPlexSans-Regular", fontSize=9.5, leading=14.5,
    textColor=GRAY_100, spaceBefore=0, spaceAfter=3,
    leftIndent=36, bulletIndent=18,
    bulletFontName="IBMPlexSans-Regular", bulletFontSize=9.5,
)
callout_style = ParagraphStyle(
    "Callout", fontName="IBMPlexSans-Italic", fontSize=9, leading=14,
    textColor=BLUE_90, leftIndent=12, rightIndent=12, spaceBefore=4, spaceAfter=4,
)
callout_attribution_style = ParagraphStyle(
    "CalloutAttribution", fontName="IBMPlexSans-Regular", fontSize=8, leading=11,
    textColor=GRAY_60, leftIndent=12, spaceBefore=0, spaceAfter=2,
)
table_header_style = ParagraphStyle(
    "TableHeader", fontName="IBMPlexSans-SemiBold", fontSize=8.5, leading=12,
    textColor=GRAY_100,
)
table_cell_style = ParagraphStyle(
    "TableCell", fontName="IBMPlexSans-Regular", fontSize=8.5, leading=12,
    textColor=GRAY_100,
)
toc_num_style = ParagraphStyle(
    "TOCNum", fontName="IBMPlexSans-Light", fontSize=14, leading=24,
    textColor=BLUE_60,
)
toc_text_style = ParagraphStyle(
    "TOCText", fontName="IBMPlexSans-Light", fontSize=14, leading=24,
    textColor=GRAY_100,
)
cover_title_style = ParagraphStyle(
    "CoverTitle", fontName="IBMPlexSans-Light", fontSize=45, leading=50,
    textColor=WHITE, spaceAfter=27,
)
cover_subtitle_style = ParagraphStyle(
    "CoverSubtitle", fontName="IBMPlexSans-Light", fontSize=24, leading=26,
    textColor=CYAN_11, spaceAfter=14,
)
cover_desc_style = ParagraphStyle(
    "CoverDesc", fontName="IBMPlexSans-Light", fontSize=14, leading=20,
    textColor=CYAN_09,
)
cover_meta_label_style = ParagraphStyle(
    "CoverMetaLabel", fontName="IBMPlexSans-Light", fontSize=12, leading=13,
    textColor=CYAN_11, spaceAfter=2,
)
cover_meta_value_style = ParagraphStyle(
    "CoverMetaValue", fontName="IBMPlexSans-Light", fontSize=14, leading=15,
    textColor=WHITE, spaceAfter=39,
)
# ============================================================
# 5. CUSTOM FLOWABLES
# ============================================================
class BlueBar(Flowable):
    def __init__(self, width=40, height=3):
        Flowable.__init__(self)
        self._bar_w = width
        self._bar_h = height
        self.width = width
        self.height = height + 4

    def draw(self):
        self.canv.setFillColor(BLUE_60)
        self.canv.rect(0, 2, self._bar_w, self._bar_h, fill=1, stroke=0)


class ThinRule(Flowable):
    def __init__(self, width=None, color=None, thickness=0.5):
        Flowable.__init__(self)
        self._rule_w = width or CONTENT_W
        self._color = color or GRAY_20
        self._thickness = thickness
        self.width = self._rule_w
        self.height = 4

    def draw(self):
        self.canv.setStrokeColor(self._color)
        self.canv.setLineWidth(self._thickness)
        self.canv.line(0, 2, self._rule_w, 2)


class CalloutBox(Flowable):
    def __init__(self, quote_text, attribution_text=None, width=None):
        Flowable.__init__(self)
        self.quote_text = quote_text
        self.attribution_text = attribution_text
        self._width = width or CONTENT_W
        self._calc_height()

    def _calc_height(self):
        inner_w = self._width - 24
        self._quote_para = Paragraph(self.quote_text, callout_style)
        qw, qh = self._quote_para.wrap(inner_w, 1000)
        self._quote_h = qh
        self._attr_h = 0
        self._attr_para = None
        if self.attribution_text:
            self._attr_para = Paragraph(
                "\u2014 " + self.attribution_text, callout_attribution_style
            )
            aw, ah = self._attr_para.wrap(inner_w, 1000)
            self._attr_h = ah
        self.height = 10 + self._quote_h + (4 if self._attr_para else 0) + self._attr_h + 10
        self.width = self._width

    def wrap(self, availWidth, availHeight):
        self._width = availWidth
        self._calc_height()
        return (self._width, self.height)

    def draw(self):
        canvas = self.canv
        canvas.setFillColor(BLUE_10)
        canvas.roundRect(0, 0, self._width, self.height, 3, fill=1, stroke=0)
        canvas.setFillColor(BLUE_60)
        canvas.rect(0, 0, 3, self.height, fill=1, stroke=0)
        y = self.height - 10 - self._quote_h
        self._quote_para.drawOn(canvas, 12, y)
        if self._attr_para:
            y = y - 4 - self._attr_h
            self._attr_para.drawOn(canvas, 12, y)


# ============================================================
# 6. EMOJI STRIPPING
# ============================================================
def strip_emoji(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "\U0001f926-\U0001f937"
        "\U00010000-\U0010ffff"
        "\u200d"
        "\u2640-\u2642"
        "\ufe0f"
        "\u2600-\u26FF"
        "\u2700-\u27BF"
        "\u23E9-\u23F3"
        "\u23F8-\u23FA"
        "\u25AA-\u25FE"
        "\u200C-\u200D"
        "\u2934-\u2935"
        "\u3030\u303D"
        "\uFE00-\uFE0F"
        "]+",
        flags=re.UNICODE,
    )
    return emoji_pattern.sub("", text)


# ============================================================
# 7. MARKDOWN PARSER
# ============================================================
def escape_xml(text):
    """Escape XML special chars for ReportLab Paragraph."""
    text = text.replace("&", "&amp;")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    return text


def format_inline(text):
    """Convert markdown inline formatting to ReportLab XML tags.

    The raw input is XML-escaped FIRST so any literal `&`, `<`, or `>` in
    body content survives without crashing ReportLab's mini-XML parser.
    Markdown tokens are then converted to tags we generate ourselves --
    those tags are not double-escaped because we control them."""
    text = escape_xml(text)
    # Bold + italic
    text = re.sub(r'\*\*\*(.+?)\*\*\*', r'<b><i>\1</i></b>', text)
    # Bold
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
    # Italic
    text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
    # Links -- only external URLs, skip internal anchors. The URL pattern
    # tolerates a single matched-paren pair (e.g. Wikipedia disambiguation
    # links: https://en.wikipedia.org/wiki/Foo_(disambiguation)).
    def _link_replace(m):
        label, url = m.group(1), m.group(2)
        if url.startswith("http://") or url.startswith("https://"):
            return f'<a href="{url}" color="#0f62fe">{label}</a>'
        return f'<b>{label}</b>'  # internal link: just bold the text
    text = re.sub(
        r'\[([^\]]+)\]\(([^\s()]+(?:\([^\s()]*\)[^\s()]*)*)\)',
        _link_replace,
        text,
    )
    return text


def _heading_text(line):
    """Return (level, text) if line is a markdown heading, else (0, '')."""
    m = re.match(r'^(#{1,6})\s+(.*)$', line.strip())
    if not m:
        return 0, ''
    return len(m.group(1)), m.group(2).strip()


def _strip_block_by_heading(md_text, heading_names):
    """Strip a heading whose text matches one of heading_names (case-insensitive),
    and everything beneath it up to the next heading. Also consume a single
    trailing '---' rule on the line directly after the block, so we don't
    leave an orphan ThinRule. Returns (block_lines_without_heading, cleaned_md_text).
    If no matching heading found, returns ([], md_text)."""
    lines = md_text.split("\n")
    targets = {h.lower() for h in heading_names}
    start = -1
    for i, line in enumerate(lines):
        level, text = _heading_text(line)
        if level and text.lower() in targets:
            start = i
            break
    if start == -1:
        return [], md_text

    # Find end: next heading line, exclusive
    end = len(lines)
    for j in range(start + 1, len(lines)):
        level, _ = _heading_text(lines[j])
        if level:
            end = j
            break

    block_lines = lines[start + 1:end]

    # Consume a trailing '---' rule (and any blank line right before it) that
    # was acting as a section terminator after this block.
    trim_end = end
    if trim_end < len(lines) and lines[trim_end].strip() in ("---", "***", "___"):
        trim_end += 1

    cleaned = "\n".join(lines[:start] + lines[trim_end:])
    return block_lines, cleaned


def extract_and_strip_toc(md_text):
    """Find a 'Contents' or 'Table of Contents' heading and parse the numbered
    list beneath it. Returns (toc_titles, md_text_without_toc_block)."""
    block_lines, cleaned = _strip_block_by_heading(
        md_text, ["contents", "table of contents"]
    )
    if not block_lines:
        return [], md_text

    titles = []
    for line in block_lines:
        m = re.match(r'^\s*\d+\.\s+(.+?)\s*$', line)
        if m:
            # Strip any markdown formatting markers from the title
            t = m.group(1).strip()
            t = re.sub(r'\*\*(.+?)\*\*', r'\1', t)
            t = re.sub(r'\*(.+?)\*', r'\1', t)
            titles.append(t)
    return titles, cleaned


def strip_cover_block(md_text):
    """Remove a '## Cover' block (heading + body + trailing rule) entirely."""
    _, cleaned = _strip_block_by_heading(md_text, ["cover"])
    return cleaned


def strip_h1_if_matches_cover(md_text, cover_title):
    """If the first H1 in the document matches cover_title (case-insensitive,
    trimmed), drop that line and a single immediately-following '---' rule.
    Avoids the cover title appearing twice when a cover page is rendered."""
    if not cover_title:
        return md_text
    lines = md_text.split("\n")
    target = cover_title.strip().lower()
    for i, line in enumerate(lines):
        level, text = _heading_text(line)
        if not level:
            continue
        if level == 1 and text.lower() == target:
            # Drop the H1 line. Also drop a single trailing '---' rule that
            # often follows a top-of-document title.
            drop_to = i + 1
            # Skip a single blank line if present before the rule
            j = drop_to
            while j < len(lines) and lines[j].strip() == "":
                j += 1
            if j < len(lines) and lines[j].strip() in ("---", "***", "___"):
                drop_to = j + 1
            return "\n".join(lines[:i] + lines[drop_to:])
        # Any other heading found before the title H1 means there's no
        # leading-title to strip; bail out.
        break
    return md_text


def suppress_leading_rule(story):
    """If the first non-Spacer flowable in the body story is a ThinRule, drop
    it. Stops a stray gray line from opening the body."""
    for i, item in enumerate(story):
        if isinstance(item, Spacer):
            continue
        if isinstance(item, ThinRule):
            del story[i]
        return story
    return story


def parse_table(lines):
    """Parse markdown table lines into ReportLab Table."""
    rows = []
    for i, line in enumerate(lines):
        line = line.strip().strip("|")
        if i == 1 and re.match(r'^[\s\-|:]+$', line):
            continue  # skip separator
        cells = [c.strip() for c in line.split("|")]
        rows.append(cells)

    if not rows:
        return None

    # Build table data with Paragraphs
    table_data = []
    for i, row in enumerate(rows):
        style = table_header_style if i == 0 else table_cell_style
        table_data.append([Paragraph(format_inline(c), style) for c in row])

    # Calculate column widths
    n_cols = len(table_data[0])
    col_w = CONTENT_W / n_cols

    t = Table(table_data, colWidths=[col_w] * n_cols, repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND',      (0, 0), (-1, 0), GRAY_10),
        ('TEXTCOLOR',       (0, 0), (-1, 0), GRAY_100),
        ('FONTNAME',        (0, 0), (-1, 0), 'IBMPlexSans-SemiBold'),
        ('FONTSIZE',        (0, 0), (-1, -1), 8.5),
        ('TOPPADDING',      (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING',   (0, 0), (-1, -1), 5),
        ('LEFTPADDING',     (0, 0), (-1, -1), 6),
        ('RIGHTPADDING',    (0, 0), (-1, -1), 6),
        ('LINEBELOW',       (0, 0), (-1, 0), 1, GRAY_100),
        ('LINEBELOW',       (0, 1), (-1, -1), 0.4, GRAY_20),
        ('VALIGN',          (0, 0), (-1, -1), 'TOP'),
        ('ROWBACKGROUNDS',  (0, 1), (-1, -1), [WHITE, HexColor("#fafafa")]),
    ]))
    return t


def parse_markdown(md_text, doc_title):
    """Parse markdown into ReportLab story (list of flowables).

    Returns just the story list. Body is rendered as continuous flow with
    inline headings; page breaks come from <!-- pagebreak --> only. Cover
    title and TOC are handled by separate preprocessing helpers."""
    lines = md_text.split("\n")
    story = []
    i = 0
    in_table = False
    table_lines = []

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Page break marker (case-insensitive). Must be checked before the
        # generic comment skip, otherwise it would be silently swallowed.
        if re.match(r'^<!--\s*page\s*break\s*-->\s*$', stripped, re.IGNORECASE):
            story.append(PageBreak())
            i += 1
            continue

        # Skip HTML comments
        if stripped.startswith("<!--"):
            comment_start = i
            # Safety limit: max 50 lines for a comment block
            while i < len(lines) and i - comment_start < 50 and "-->" not in lines[i]:
                i += 1
            # Skip the closing line if found
            if i < len(lines) and "-->" in lines[i]:
                i += 1
            continue

        # Table detection
        if stripped.startswith("|") and not in_table:
            in_table = True
            table_lines = [stripped]
            i += 1
            continue
        elif in_table:
            if stripped.startswith("|"):
                table_lines.append(stripped)
                i += 1
                continue
            else:
                # End of table
                t = parse_table(table_lines)
                if t:
                    story.append(t)
                    story.append(Spacer(1, 8))
                in_table = False
                table_lines = []
                # Don't increment i, re-process this line
                continue

        # Horizontal rule
        if stripped in ("---", "***", "___"):
            # Skip the very first line (treat a leading rule as YAML
            # frontmatter delimiter rather than a body rule).
            if i > 0:
                story.append(ThinRule())
                story.append(Spacer(1, 6))
            i += 1
            continue

        # H1 -- inline only. No PageBreak, no BlueBar treatment. The cover
        # page (if rendered) handles the document title; preprocessing strips
        # a leading H1 that matches the cover title.
        if stripped.startswith("# ") and not stripped.startswith("## "):
            title = stripped[2:].strip()
            story.append(Paragraph(format_inline(title), section_title_style))
            i += 1
            continue

        # H2 -- inline only. Render verbatim so authored numbering ("1. Foo")
        # is preserved in the body. The TOC display strips numbering separately.
        if stripped.startswith("## "):
            title = stripped[3:].strip()
            story.append(Paragraph(format_inline(title), h2_style))
            i += 1
            continue

        # H3
        if stripped.startswith("### ") and not stripped.startswith("#### "):
            title = stripped[4:].strip()
            story.append(Paragraph(format_inline(title), h3_style))
            i += 1
            continue

        # H4/H5/H6 — render at H3 size (smallest heading style we have)
        if stripped.startswith("#### "):
            title = stripped.lstrip("#").strip()
            story.append(Paragraph(format_inline(title), h3_style))
            i += 1
            continue

        # Blockquote -> CalloutBox
        if stripped.startswith("> "):
            quote_lines = []
            quote_start = i
            # Safety limit: max 20 lines per quote
            while i < len(lines) and i - quote_start < 20 and lines[i].strip().startswith("> "):
                q = lines[i].strip()[2:].strip()
                # Strip italic markers from quotes
                q = re.sub(r'^\*"?|"?\*$', '', q)
                q = q.strip('"').strip()
                quote_lines.append(q)
                i += 1

            quote_text = " ".join(quote_lines)
            
            # Limit quote length to prevent ReportLab issues
            if len(quote_text) > 1000:
                quote_text = quote_text[:1000] + "..."

            # Check for attribution on next line
            attribution = None
            if i < len(lines):
                next_line = lines[i].strip()
                # Match patterns like "-- Name, ID" or "> -- Name"
                attr_match = re.match(r'^(?:>?\s*)?(?:\u2014|--|---)\s*(.+)$', next_line)
                if attr_match:
                    attribution = attr_match.group(1).strip()
                    i += 1

            try:
                story.append(Spacer(1, 8))
                story.append(KeepTogether([
                    CalloutBox(
                        escape_xml(quote_text),
                        escape_xml(attribution) if attribution else None,
                    )
                ]))
                story.append(Spacer(1, 8))
            except Exception as e:
                print(f"WARNING: Failed to create quote at line {quote_start}: {e}", file=sys.stderr)
                # Skip this quote and continue
                pass
            continue

        # Sub-bullet (indented)
        if re.match(r'^  +[-*]\s', line):
            text = re.sub(r'^\s+[-*]\s+', '', line).strip()
            story.append(Paragraph(
                f'<bullet>\u2022</bullet>{format_inline(text)}',
                sub_bullet_style
            ))
            i += 1
            continue

        # Bullet
        if stripped.startswith("- ") or stripped.startswith("* "):
            text = stripped[2:].strip()
            story.append(Paragraph(
                f'<bullet>\u2014</bullet>{format_inline(text)}',
                bullet_style
            ))
            i += 1
            continue

        # Empty line
        if not stripped:
            i += 1
            continue

        # Body text
        # Collect consecutive non-empty, non-special lines
        para_lines = []
        start_i = i
        while i < len(lines):
            # Safety check: prevent infinite loops
            if i - start_i > 100:
                print(f"WARNING: Breaking paragraph collection at line {i} (too many lines)", file=sys.stderr)
                break
            
            l = lines[i].strip()
            if not l or l.startswith("#") or l.startswith("|") or l.startswith(">") or l.startswith("- ") or l.startswith("* ") or l.startswith("<!--") or re.match(r'^  +[-*]\s', lines[i]):
                break
            para_lines.append(l)
            i += 1

        if para_lines:
            text = " ".join(para_lines)
            # Limit text length to prevent ReportLab hangs
            if len(text) > 3000:
                text = text[:3000] + "..."
            try:
                story.append(Paragraph(format_inline(text), body_style))
            except Exception as e:
                print(f"WARNING: Failed to create paragraph at line {start_i}: {e}", file=sys.stderr)
                # Skip this paragraph and continue
                pass
        else:
            # Current line is unrecognized (matched an inner-loop break condition
            # that the outer loop doesn't explicitly handle — e.g. a bare ">",
            # a "#foo" with no space, or a heading level we don't render).
            # Advance unconditionally so we never spin on the same line.
            print(f"WARNING: Skipping unrecognized line {i}: {lines[i][:80]!r}", file=sys.stderr)
            i += 1

    # Flush remaining table
    if in_table and table_lines:
        t = parse_table(table_lines)
        if t:
            story.append(t)

    return story


# ============================================================
# 8. PAGE CALLBACKS
# ============================================================
# Path to IBM Rebus totem logo. Script lives in <skill>/scripts/,
# asset lives in <skill>/assets/.
LOGO_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "ibm-rebus-totem.svg")
# Fallback: check home directory for direct skill install
if not os.path.exists(LOGO_PATH):
    LOGO_PATH = os.path.expanduser("~/.bob/skills/document-conversion/assets/ibm-rebus-totem.svg")


def cover_page_cb(canvas, doc):
    canvas.saveState()
    # Background fill
    canvas.setFillColor(COVER_BG)
    canvas.rect(0, 0, PAGE_W, PAGE_H, fill=1, stroke=0)
    # Accent line
    canvas.setStrokeColor(CYAN_11)
    canvas.setLineWidth(1)
    accent_y = PAGE_H - 122
    canvas.line(LEFT_MARGIN, accent_y, LEFT_MARGIN + CONTENT_W, accent_y)
    # Logo (bottom-right)
    if os.path.exists(LOGO_PATH):
        from reportlab.graphics import renderPDF
        try:
            from svglib.svglib import svg2rlg
            drawing = svg2rlg(LOGO_PATH)
            if drawing:
                scale_w = 45 / drawing.width
                scale_h = 100 / drawing.height
                scale = min(scale_w, scale_h)
                drawing.width *= scale
                drawing.height *= scale
                drawing.scale(scale, scale)
                logo_x = PAGE_W - 57 - drawing.width
                logo_y = 57
                renderPDF.draw(drawing, canvas, logo_x, logo_y)
        except ImportError:
            pass  # svglib not installed, skip logo
    canvas.restoreState()


def content_page_cb(canvas, doc, document_title="", report_date=""):
    """Footer-only page decoration. Document title and report date are
    bound by the caller via functools.partial so we don't lean on globals."""
    canvas.saveState()
    # Footer only -- no top header. Page number lives on the footer right.
    canvas.setStrokeColor(GRAY_20)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_MARGIN, BOTTOM_MARGIN - 0.15 * inch, PAGE_W - RIGHT_MARGIN, BOTTOM_MARGIN - 0.15 * inch)
    canvas.setFont("IBMPlexSans-Regular", 6.5)
    canvas.setFillColor(GRAY_50)
    footer_left = f"IBM Design Language  |  {document_title}  |  {report_date}"
    footer_right = f"IBM Confidential  ·  Page {doc.page}"
    canvas.drawString(LEFT_MARGIN, BOTTOM_MARGIN - 0.35 * inch, footer_left)
    canvas.drawRightString(PAGE_W - RIGHT_MARGIN, BOTTOM_MARGIN - 0.35 * inch, footer_right)
    canvas.restoreState()


# ============================================================
# 9. BUILD DOCUMENT
# ============================================================
def build_cover(title, subtitle=None, description=None, study_date=None, team=None):
    """Build cover page story elements. Only title is required.

    All caller-supplied strings are XML-escaped before going to ReportLab
    so a literal `&` in a CLI argument (e.g. --team "AI & Research")
    doesn't crash the build."""
    story = []
    story.append(Spacer(1, 1.7 * inch))
    story.append(Paragraph(escape_xml(title), cover_title_style))
    if subtitle:
        story.append(Paragraph(escape_xml(subtitle), cover_subtitle_style))
    if description:
        story.append(Paragraph(escape_xml(description), cover_desc_style))

    # Only add metadata section if there's metadata to show
    has_metadata = study_date or team
    if has_metadata:
        # Push metadata toward bottom
        story.append(Spacer(1, 2.5 * inch))
        if study_date:
            story.append(Paragraph("Research date", cover_meta_label_style))
            story.append(Paragraph(escape_xml(study_date), cover_meta_value_style))
        if team:
            story.append(Paragraph("Team", cover_meta_label_style))
            story.append(Paragraph(escape_xml(team), cover_meta_value_style))

    story.append(PageBreak())
    return story


def build_toc(toc_titles):
    """Build the polished blue-numbered table of contents page from a list of
    titles. Returns [] when toc_titles is empty (caller decides whether the
    Contents block was found in the markdown)."""
    if not toc_titles:
        return []

    story = []
    story.append(Spacer(1, 0.3 * inch))
    story.append(BlueBar(40, 3))
    story.append(Spacer(1, 6))
    story.append(Paragraph("Contents", ParagraphStyle(
        "TOCTitle", fontName="IBMPlexSans-Light", fontSize=28, leading=32,
        textColor=GRAY_100, spaceAfter=16,
    )))
    story.append(ThinRule(color=GRAY_100, thickness=0.75))
    story.append(Spacer(1, 12))

    for idx, title in enumerate(toc_titles, 1):
        # Strip authored leading numbering ("1. Foo") for the display only —
        # the blue "01" badge replaces it.
        display = re.sub(r'^\s*\d+\.\s*', '', title).strip()
        num = f"{idx:02d}"
        row = [[Paragraph(num, toc_num_style),
                Paragraph(escape_xml(display), toc_text_style)]]
        t = Table(row, colWidths=[0.6 * inch, 5.5 * inch])
        t.setStyle(TableStyle([
            ('VALIGN',     (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('LINEBELOW',  (0, 0), (-1, -1), 0.3, GRAY_20),
        ]))
        story.append(t)

    story.append(PageBreak())
    return story


def _default_title_from_path(md_path):
    base = os.path.splitext(os.path.basename(md_path))[0]
    return base.replace("-", " ").replace("_", " ").strip().title() or "IBM Report"


def build_document(md_path, output_path, cover=False, title=None, subtitle=None,
                   description=None, study_date=None, team=None, font_dir=None, interactive=True):
    # Register fonts here (not at import time) so --help and argparse
    # errors don't crash on missing TTF files.
    register_fonts(cli_font_dir=font_dir, interactive=interactive)

    with open(md_path, "r", encoding="utf-8") as f:
        md_text = f.read()

    md_text = strip_emoji(md_text)

    # Resolve metadata strictly from CLI args -- no markdown sniffing.
    document_title = title or _default_title_from_path(md_path)
    report_date = study_date or datetime.now().strftime("%B %Y")

    # Preprocessing pipeline: strip the boilerplate blocks out of the source
    # before parse_markdown sees them, so the parser stays dumb and renders
    # whatever's left as continuous body content.
    toc_titles, md_text = extract_and_strip_toc(md_text)
    md_text = strip_cover_block(md_text)
    if cover:
        md_text = strip_h1_if_matches_cover(md_text, document_title)

    # Body story
    content_story = parse_markdown(md_text, document_title)
    content_story = suppress_leading_rule(content_story)

    # Compose the full document story
    story = []

    if cover:
        story.extend(build_cover(
            document_title,
            subtitle,
            description,
            study_date or report_date,
            team,
        ))

    story.extend(build_toc(toc_titles))
    story.extend(content_story)

    # Build PDF
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=LEFT_MARGIN,
        rightMargin=RIGHT_MARGIN,
        topMargin=TOP_MARGIN + 0.15 * inch,
        bottomMargin=BOTTOM_MARGIN,
        title=document_title,
        author="IBM",
    )

    # Bind document_title / report_date into the content footer callback
    # via partial so we don't reach for module globals.
    content_cb = partial(
        content_page_cb,
        document_title=document_title,
        report_date=report_date,
    )
    first_page_cb = cover_page_cb if cover else content_cb

    try:
        print(f"Building PDF with {len(story)} elements...", file=sys.stderr, flush=True)
        doc.build(story, onFirstPage=first_page_cb, onLaterPages=content_cb)
        print(f"PDF generated successfully: {output_path}")
        return output_path
    except Exception as e:
        print(f"ERROR during PDF build: {e}", file=sys.stderr)
        raise


# ============================================================
# 10. CLI
# ============================================================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate IBM-branded PDF from markdown")
    parser.add_argument("markdown_file", help="Path to markdown file")
    parser.add_argument("output_pdf", help="Path for output PDF")
    parser.add_argument("--cover", action="store_true", help="Render the cool blue cover page")
    parser.add_argument("--title", help="Cover title (also used for footer/PDF metadata)")
    parser.add_argument("--subtitle", help="Cover subtitle")
    parser.add_argument("--description", help="Small descriptive text on the cover")
    parser.add_argument("--date", help="Date shown on cover and in footer (e.g., 'April 2026')")
    parser.add_argument("--team", help="Team name shown on cover (e.g., 'IBM UX Research')")
    parser.add_argument(
        "--font-dir",
        help=(
            "Directory containing IBMPlexSans-*.ttf files. "
            "Defaults to ~/Documents/IBM_Plex_Sans/static, then the skill's "
            "assets/fonts/ directory, then system font directories."
        ),
    )
    parser.add_argument(
        "--no-interactive",
        action="store_true",
        help="Disable interactive font download/location prompt if fonts not found",
    )

    args = parser.parse_args()

    if not os.path.exists(args.markdown_file):
        print(f"Error: File not found: {args.markdown_file}")
        sys.exit(1)

    build_document(
        args.markdown_file,
        args.output_pdf,
        cover=args.cover,
        title=args.title,
        subtitle=args.subtitle,
        description=args.description,
        study_date=args.date,
        team=args.team,
        font_dir=args.font_dir,
        interactive=not args.no_interactive,
    )
