#!/bin/sh
# Build rubrics/ — per-gate excerpts of EVALUATION-LOOP.md.
#
# EVALUATION-LOOP.md is canonical and stays whole. But a checker session only
# needs the verdict schema (§2) and its own Definition-of-Done rubric (§4.x),
# and a chat tool loads files whole — so a guide-checker run otherwise carries
# six other gates' rubrics, the gate matrix, and both checkpoints as dead
# weight. These excerpts are what to paste (or point Bob at) alongside one
# checker. They are generated, never edited: edit EVALUATION-LOOP.md, run
# this, commit both. Headings and item numbers are copied verbatim, so a
# citation like "§4.6 item 2" resolves identically in either file.
set -e
cd "$(dirname "$0")"
SRC=EVALUATION-LOOP.md
OUT=rubrics

[ -f "$SRC" ] || { echo "missing $SRC" >&2; exit 1; }

# Print one section: from the line starting with $1 up to (not including) the
# next heading of the same or higher level. A "## " section keeps its "### "
# subsections; a "### " section stops at either level.
section() {
  case "$1" in
    '## '*)  stop='/^## /' ;;
    *)       stop='/^## / || /^### /' ;;
  esac
  awk -v s="$1" '
    index($0, s) == 1 { p = 1; print; next }
    p && ('"$stop"') { exit }
    p { print }
  ' "$SRC"
}

emit() {  # emit <heading-prefix> <slug>
  f="$OUT/$2.md"
  {
    printf '<!-- GENERATED by build-rubrics.sh from EVALUATION-LOOP.md.\n'
    printf '     Do not edit this file. Edit EVALUATION-LOOP.md and rebuild. -->\n\n'
    printf '# Rubric excerpt — %s\n\n' "$1"
    printf 'For a checker session that cannot carry all of `EVALUATION-LOOP.md`:\n'
    printf 'paste this file alongside the checker agent. Item numbers are verbatim,\n'
    printf 'so citations like "%s item 2" resolve here. The loop itself — gate\n' "${1%% *}"
    printf 'matrix, iteration cap, escalation, known limits, checkpoints — lives in\n'
    printf 'the full file and is not restated.\n\n'
    section '## 2. Verdict schema'
    printf '\n'
    section "### $1"
  } > "$f"
  # A heading that stops matching would produce a schema-only stub — fail loud.
  [ "$(grep -c "^### $1" "$f")" = 1 ] || { echo "extraction failed for: $1" >&2; exit 1; }
  echo "built $f"
}

rm -rf "$OUT"
mkdir "$OUT"

emit '4.1 Research plan'                          '4.1-research-plan'
emit '4.2 Synthesis findings'                     '4.2-synthesis-findings'
emit '4.3 Competitive analysis'                   '4.3-competitive-analysis'
emit '4.4 Readout deck'                           '4.4-readout-deck'
emit '4.5 Theme set — the human checkpoint'       '4.5-theme-set'
emit '4.6 Discussion guide / interview script'    '4.6-discussion-guide'
emit '4.7 Survey instrument'                      '4.7-survey-instrument'
emit '4.8 Findings report'                        '4.8-findings-report'
emit '4.9 Customer impact summary'                '4.9-customer-impact-summary'
